export interface GameDef {
  id: string;
  name: string;
  playerLabel: string;
  minPlayers: number;
  maxPlayers: number;
  difficulty: number;
  scoringType: string;
  description: string;
  defaultTarget: number;
  isTeam: boolean;
  lowerIsBetter: boolean;
  eliminationScore?: number;
  defaultRounds?: number;
  icon: string;
}

export const GAMES: GameDef[] = [
  {
    id: "tarneeb",
    name: "طرنيب عادي",
    playerLabel: "٤ لاعبين",
    minPlayers: 4,
    maxPlayers: 4,
    difficulty: 3,
    scoringType: "طلبات + لطشات",
    description: "لعبة فريقين مع مزايدة على الحكم",
    defaultTarget: 41,
    isTeam: true,
    lowerIsBetter: false,
    icon: "spade",
  },
  {
    id: "tarneeb_sy",
    name: "طرنيب سوري ٤١",
    playerLabel: "٤ لاعبين",
    minPlayers: 4,
    maxPlayers: 4,
    difficulty: 3,
    scoringType: "طلبات + لطشات",
    description: "طرنيب بحكم معكوس — الحكم ضد لون آخر طاح",
    defaultTarget: 41,
    isTeam: true,
    lowerIsBetter: false,
    icon: "spade",
  },
  {
    id: "400",
    name: "٤٠٠ (أربعمية)",
    playerLabel: "٤ لاعبين",
    minPlayers: 4,
    maxPlayers: 4,
    difficulty: 4,
    scoringType: "نقاط فردية",
    description: "مزايدة فردية، أول واحد يوصل ٤١ يفوز",
    defaultTarget: 41,
    isTeam: false,
    lowerIsBetter: false,
    icon: "diamond",
  },
  {
    id: "terkis",
    name: "تركس فردي",
    playerLabel: "٤ لاعبين",
    minPlayers: 4,
    maxPlayers: 4,
    difficulty: 4,
    scoringType: "ممالك + عقود",
    description: "تجنب اللطشات والديناري والبنات والشيخ",
    defaultTarget: -300,
    isTeam: false,
    lowerIsBetter: true,
    icon: "crown",
  },
  {
    id: "terkis_team",
    name: "تركس شراكة",
    playerLabel: "٤ لاعبين",
    minPlayers: 4,
    maxPlayers: 4,
    difficulty: 4,
    scoringType: "فرق + ممالك",
    description: "تركس بشراكة — الفريق اللي درجاته أعلى يفوز",
    defaultTarget: -300,
    isTeam: true,
    lowerIsBetter: true,
    icon: "crown",
  },
  {
    id: "terkis_complex",
    name: "تركس كومبلكس",
    playerLabel: "٤ لاعبين",
    minPlayers: 4,
    maxPlayers: 4,
    difficulty: 5,
    scoringType: "ممالك + كومبلكس",
    description: "تركس بقواعد متقدمة — للمحترفين",
    defaultTarget: -300,
    isTeam: false,
    lowerIsBetter: true,
    icon: "crown",
  },
  {
    id: "hand",
    name: "هاند / كنكان",
    playerLabel: "٢-٦ لاعبين",
    minPlayers: 2,
    maxPlayers: 6,
    difficulty: 3,
    scoringType: "أقل نقاط يفوز",
    description: "افرغ يدك أول — اللي يوصل ١٠١ يطلع",
    defaultTarget: 101,
    isTeam: false,
    lowerIsBetter: true,
    eliminationScore: 101,
    icon: "hand",
  },
  {
    id: "baloot",
    name: "بلوت",
    playerLabel: "٤ لاعبين",
    minPlayers: 4,
    maxPlayers: 4,
    difficulty: 4,
    scoringType: "سن + حكم + لطشات",
    description: "لعبة خليجية شهيرة — أول فريق يوصل ١٥٢",
    defaultTarget: 152,
    isTeam: true,
    lowerIsBetter: false,
    icon: "club",
  },
  {
    id: "basra",
    name: "بصرة",
    playerLabel: "٢-٤ لاعبين",
    minPlayers: 2,
    maxPlayers: 4,
    difficulty: 2,
    scoringType: "التقاط + بصرة",
    description: "اجمع أكثر الأوراق وخذ البصرات",
    defaultTarget: 121,
    isTeam: false,
    lowerIsBetter: false,
    icon: "heart",
  },
  {
    id: "leekha",
    name: "ليخة",
    playerLabel: "٤ لاعبين",
    minPlayers: 4,
    maxPlayers: 4,
    difficulty: 3,
    scoringType: "أقل نقاط يفوز",
    description: "تجنب القلوب وبنت سبايا والداما",
    defaultTarget: 101,
    isTeam: false,
    lowerIsBetter: true,
    icon: "heart",
  },
  {
    id: "domino",
    name: "دومينو",
    playerLabel: "٢-٤ لاعبين",
    minPlayers: 2,
    maxPlayers: 4,
    difficulty: 2,
    scoringType: "نقاط الأحجار",
    description: "صفّر يدك أولاً واجمع نقاط أحجار الخصم",
    defaultTarget: 100,
    isTeam: true,
    lowerIsBetter: false,
    icon: "grid",
  },
  {
    id: "jackaroo",
    name: "جاكارو عادي",
    playerLabel: "٤ لاعبين",
    minPlayers: 4,
    maxPlayers: 4,
    difficulty: 3,
    scoringType: "فريق يفوز",
    description: "أوصل حجارتك الثمانية للبيت قبل الخصم",
    defaultTarget: 0,
    isTeam: true,
    lowerIsBetter: false,
    icon: "circle",
  },
  {
    id: "jackaroo_cx",
    name: "جاكارو كومبلكس",
    playerLabel: "٤ لاعبين",
    minPlayers: 4,
    maxPlayers: 4,
    difficulty: 5,
    scoringType: "فريق يفوز",
    description: "جاكارو بقواعد القتل — للشياطين",
    defaultTarget: 0,
    isTeam: true,
    lowerIsBetter: false,
    icon: "circle",
  },
  {
    id: "harreega",
    name: "حريقة",
    playerLabel: "٤ لاعبين",
    minPlayers: 4,
    maxPlayers: 4,
    difficulty: 3,
    scoringType: "نقاط خاصة",
    description: "حرّق أوراق الخصم واجمع أكبر رقم",
    defaultTarget: 200,
    isTeam: false,
    lowerIsBetter: false,
    icon: "flame",
  },
  {
    id: "nthaleh",
    name: "نذالة",
    playerLabel: "٤ لاعبين",
    minPlayers: 4,
    maxPlayers: 4,
    difficulty: 2,
    scoringType: "نقاط خاصة",
    description: "لعبة خفيفة — الأوراق بتحكم على بعض",
    defaultTarget: 150,
    isTeam: false,
    lowerIsBetter: false,
    icon: "star",
  },
  {
    id: "estimation",
    name: "إستميشن",
    playerLabel: "٤ لاعبين",
    minPlayers: 4,
    maxPlayers: 4,
    difficulty: 4,
    scoringType: "مزايدة + لطشات",
    description: "بيد كم لطشة بتاخذ — ١٨ جولة، مجموع البيد ما يساوي ١٣",
    defaultTarget: 0,
    isTeam: false,
    lowerIsBetter: false,
    defaultRounds: 18,
    icon: "target",
  },
  {
    id: "ksara",
    name: "كسرة",
    playerLabel: "٤ لاعبين",
    minPlayers: 4,
    maxPlayers: 4,
    difficulty: 5,
    scoringType: "ممالك + ٤ ألعاب",
    description: "٤ ممالك — كومبلكس + طرنيب + لطشين + تركس لكل مملكة",
    defaultTarget: 0,
    isTeam: false,
    lowerIsBetter: false,
    icon: "layers",
  },
  {
    id: "kout_bo",
    name: "كوت بو",
    playerLabel: "٤ لاعبين",
    minPlayers: 4,
    maxPlayers: 4,
    difficulty: 3,
    scoringType: "فريقين + كوت",
    description: "أول فريق يوصل ٧ نقاط يفوز — ٧+ لطشات كوت، ١٣ كوت بو",
    defaultTarget: 7,
    isTeam: true,
    lowerIsBetter: false,
    icon: "award",
  },
];

export const getGameById = (id: string): GameDef | undefined =>
  GAMES.find((g) => g.id === id);
